dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: pnYMC8bD7dq7lT3c/hVKRcnTRrMqTaeO9WxaEQAKABuudnK1pFN5+G+BWbHvAe97p1iglfeO95EAeeMsY2ThCQONLuToaFJ8HsJ9uoN+lP1jHo9f9dqVvJ0j5VDHb2oDWNayAyG+HB3YkKEE5pFqeVQWEvnr1670S+dOIXUHk1BF+GwFce8tB9yj7ECPOnL2J8oqZZy5j6aTQh06YdbdcbluXM5svF3uhVV9VAoYBY+bF6wnyYtERlSIbJGnKvJ0zKXbBuj30edwk9zF622awz2vNRv88IkItRFrgdrb5abYS4sr3LQz+VTnNtBd640SicEpQSAeURuLyxxepMvJZJ9MPi8eZ7ExmqQ5XOBJfwt/DJ60wQDHWVg5RcsSq62mK+Q3klYHbQnjj/8C2Sx2iURxir/KGaeaN8QMR7NKuG36DenNQHPDvlU7AJ5cYh+KNhFf7oAiZzaoJAxTwSsM/tmBT2CxuqY5eSVBhOE45KcaQj8Phkv3iQJjKnrhKgQmEvNnrLgazE1hAFaxzLguIlFY69VqvNfF2P7uwdd+C7JQkrxOzl92eLvD1mROe74+jK2g7pMqqRvzsSt64m9XNSQ8NiowYvkf/zATpbtcOeQvnZNS2bAgxVe72dpBrzcBxviJV+KfASFFYJ1LGaEHXfDsPkefzWqu+o3bor9VWNo=
  - secure: F2cSffH/Dc3YxySBRUHzpTzOspDanMUHMX4AM+8w6o2clVLLqtahV4fcgpDsHQmdvvixNOffrdHRSimu5240SWAipGnjFcItn+mi93oLB9vPbGSjTdMp7CR1egOnjvGNDpB/jyZSyrA/tTrX0KCVuQKj4Xgv1e38hh10LJSQIGqfeaMcd00T/aOCJxUCztvvy62z21zjo7YwhCR9rEFWVAEy2CsmZju4b8ussf1j8WWALxOLb37uujsDh3EPvTa3V6fWSIjAH6HBIvwdenHjz4KUm/9JcWd3omkPZOB+e9z0BcN5HTmPYE4XQXRGE3HhkmiIoqaBTTDaqefNW5cSgPDozoHt9bwlnWcAMDVc2X5ct6hx14Xe0Crvdtmg3zHkyBaPpNYcOZoe1pRQa+TwgukZlNkA/0VDxoq4ZPMCfv2H8NcblOQcYzSLWYdQCq7Z06JUWM5JdFPtAJjHPhnEE9zJBEWgnA9Xa+/VhT6xMVx81juuEW34NB1TeMnTXIP+eoCuCtQFS3DJqqTE6xwMpKO2+fvTVyK0GBfc4aUZYZPe/cLk6oWrojFXanyUySM6GTH9VWKfL/ptpmGqfgy/1SZJLo+QHoJh30Urz9LBS+sxsBKRI6yT1k3s+cxU63fT6tPUnFrHlmM/YnEXsEkOm+oosaLVfk7CyYYvzwImjk8=
  - secure: fXknknjqoVwU9O/lMMcdpBCYOJY9m8DlSH5Ta7wvlP27edg/Zx5kufUuNWDzAjDdGCVKLijiktFHhmIHbHS4fEscpqgn7edOHCDGM2McO9EV7EpFTfUiIodhDWhs+U8JL1dFbjnq5mgYbtFv7W1eewExrPaZu+NBECBJTx81MHVuaUAl1/N5Rwq8grFjoLrpIZocwhbluX9xobvDopDg/H2Oj5jSMZ5wLKKyHUX0x87Rj6pe3bH8uhkgaWqEkC9kB3b8odSUVq9d7lrtaGfwz8rQ241tR8OtgZGb/djVzm1CRETYJCfmJk0FjTBc0rIH+6I/OAgoY62YUjOsj4QlxysZpY8VsLCE9Ivo+8EnbSLUJkjMvq/5klXHgV0qwYgaWfnNXSIbQj2MUkdiFwxQ7/h7RE/LfQFFdJUbD1j5se1fhsOaBxl+5ERH21Aflqeqoga/ywPqoGlcMWUlUOPHjB4n9Gn9jr2VJfdpiRkC/r4Qoe9RQPxvxfxPqqmiTrhDPrDbG0Lif2Iis9X70dZfpNRkCToefekBXqvDj3zAcnLy7koW9ALWThQMxjQnvdohxnw//vHMvOqQL3TpNAI0oGy57Dm4bXFNCX93A8I2EFCB+NN5Iq5UOqXOuLK7CNfnUOzz1j5GSZpqjHPOJ50TdG7vDduYcQlLfh8qg8+Dxpk=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
